# -*- coding: utf-8 -*-
{
    "name": "ODOTRANS Dispatch",
    "version": "2.0.0",
    "category": "Inventory/Delivery",
    "summary": "Trips, manifests, assignment board",
    "author": "SA Systems",
    "maintainer": "SA Systems",
    "website": "https://www.sasystems.solutions",
    "support": "info@sasystems.solutions",
    "license": "LGPL-3",
    "depends": ["odotrans_tms", "odotrans_fleet"],
    "data": [
        "security/odotrans_dispatch_security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "data/event_subscription_data.xml",
        "views/trip_views.xml",
        "views/manifest_views.xml",
        "views/menus.xml",
        "wizards/assign_wizard_views.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
